# In CargoPro_Rest/docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15-alpine # Use a lightweight PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: cargopro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: la@150903 # IMPORTANT: Use a strong password
    ports:
      - "5433:5432" # Map container port 5432 to host port 5432
    volumes:
      - cargopro_data:/var/lib/postgresql/data # Persist database data

  app:
    build: ./LoaderBooker # Tells Docker Compose to build the image from the Dockerfile in the LoaderBooker directory
    restart: on-failure
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cargopro_db # 'db' is the service name defined in this file
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: la@150903 # Must match the password for the db service
      # Set other properties if needed, e.g., for JWT secret or other dynamic configs
    depends_on:
      - db # Ensures the database container starts before the application container
    # If your app needs more time to connect to DB, you might add healthchecks or wait-for-it scripts
    # For simple cases, depends_on is often sufficient.

volumes:
  cargopro_data: # Define the named volume for data persistence